USE EMPRESA_VENDAS
/*CREATE DATABASE EMPRESA_VENDAS; */


/*CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INTEGER PRIMARY KEY,
	NOME_FORNECEDOR VARCHAR(50),
	CONTATO INTEGER,
	ENDEREÇO TEXT,
);*/

/*CREATE TABLE AQUISIÇÃO(
    ID_AQ INTEGER PRIMARY KEY,
	PRODUTOS_ENVIADOS VARCHAR(100),
	FORNECEDOR INTEGER FOREIGN KEY REFERENCES FORNECEDOR(ID_FORNECEDOR) NOT NULL,
	QUANTIDADE INTEGER,
	PREÇO_AQUISIÇÃO DECIMAL(10,2),
	DATA_AQUISIÇÃO DATE

);*/

/*CREATE TABLE CLIENTES(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME_CLIENTE VARCHAR(50),
	ENDEREÇO TEXT,
	TELEFONE BIGINT ,
	EMAIL VARCHAR(255),
	DATA_CADASTRO DATE
);*/

/*CREATE TABLE PRODUTO(
	ID_PRODUTO INTEGER PRIMARY KEY,
	NOME_PRODUTO VARCHAR(100),
	CATEGORIA VARCHAR(100),
	DESCRIÇÃO TEXT,
	QUANTIDADE INTEGER,
	PREÇO DECIMAL(10,2)
);*/

/*CREATE TABLE SETOR(
	ID_SETOR INTEGER PRIMARY KEY,
	NOME_SETOR VARCHAR,
	DESCRIÇÃO VARCHAR(155),
	NUMERO_FUNCIONARIOS INTEGER
);*/


/*CREATE TABLE VENDAS(
	ID_VENDA INTEGER PRIMARY KEY,
	CLIENTE_COMPRADOR VARCHAR(11) FOREIGN KEY REFERENCES CLIENTES(CPF),
	PRODUTO_VENDIDO INTEGER FOREIGN KEY REFERENCES PRODUTO(ID_PRODUTO),
	PAGAMENTO VARCHAR(25)
);*/

/*CREATE TABLE FUNCIONARIOS(
	ID_FUNC INTEGER PRIMARY KEY,
	NOME_FUNC VARCHAR(155),
	CARGO TEXT,
	SALARIO DECIMAL(10,2),
	HORAS_TRABALHADAS VARCHAR(55),
	SETOR INTEGER FOREIGN KEY REFERENCES SETOR (ID_SETOR)
);*/

/*CREATE TABLE ITENS_VENDA(
   ID_ITEM INTEGER PRIMARY KEY,
   ID_VENDA INTEGER FOREIGN KEY REFERENCES VENDAS(ID_VENDA),
   PRODUTO INTEGER FOREIGN KEY REFERENCES PRODUTO(ID_PRODUTO),
   QUANTIDADE_VENDIDA INTEGER
);*/
 
/*CREATE DATABASE EMPRESA_VENDAS;

CREATE TABLE CLIENTE(
  ID_CLIENTE INTEGER PRIMARY KEY NOT NULL,
  NOME VARCHAR(50),
  EMAIL VARCHAR(100),
  CPF INTEGER,
  TELEFONE INTEGER(15),
  ENDEREÃ‡O VARCHAR(100)
  
);*/

/*CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INTEGER PRIMARY KEY NOT NULL,
	NOME VARCHAR(50),
	CNPJ TEXT,
	CONTATO INTEGER(15)
);*/
 
/*INSERT INTO CLIENTES VALUES('76263790040','MARCOS ROBERTO CARVALHO','RUA DOM ALMENDRA DOS REIS, 15555',684896321,'ROBERTITO@GMAIL.COM','2021-11-20')*/
/*INSERT INTO FORNECEDOR VALUES(5,'LEANDRO(FORNECEDOR MÓVEIS)','256995441','RUA EUNICO,0233')*/
/*INSERT INTO PRODUTO VALUES(100,'COMPUTADOR INTEL HD','TECNOLOGIA','UM COMPUTADOR DOS MAIS MODERNOS LANÇADOS PELA INTEL. ANO 2024, COM UMA MEMÓRIA RESISTENTE E POTENTE',50,2600.50)*/
/*INSERT INTO SETOR VALUES(200,'FINANCEIRO','DEPARTAMENTO RESPONSÁVEL POR CUIDAR DO DINHEIRO E DAS FINANÇAS ',45)*/
/*INSERT INTO AQUISI��O VALUES(1,'PRODUTOS ELETRÔNICOS',1,22);*/

/*UPDATE CLIENTES
SET NOME_SETOR = 2
WHERE NOME_SETOR = 'FINANCEIRO'*/

/*SELECT FRN.NOME_FORNECEDOR, FRN.ID_FORNECEDOR,FRN.ENDEREÇO
FROM FORNECEDOR FRN
WHERE FRN.ENDEREÇO = '[O]'*/


/*CREATE TABLE PAGAMENTO (
  ID_PGTO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1) ,
  ID_VENDA INTEGER FOREIGN KEY REFERENCES VENDAS(ID_VENDA),
  TIPO_DE_PAGAMENTO VARCHAR(50) NOT NULL,
  VALOR_PAGO VARCHAR(50) NOT NULL,
  DATA_PAGAMENTO DATE NOT NULL 
);*/

/*CREATE INDEX INDEX_NOME_CLIENTE
ON CLIENTES(NOME_CLIENTE)*/


INSERT INTO CLIENTES VALUES('97562721041','EDGAR N�BREGA','RUA LEMITE AYRES,2',9935080133,'EDGAR@GMAIL.COM','2015-05-15')
INSERT INTO VENDAS VALUES(600,39898403047,600,'DINHEIRO(ESP�CIE)');
INSERT INTO PRODUTO VALUES(600,'PLAYSTATION 5 ','EQUIPAMENTO TECNOL�GICO','VIDEOGAME MAIS MODERNO DA SONY COM EXCELENTE QUALIDADE E COM EXCELENTES JOGOS PARA SE DIVERTIR',50,3900.00)
INSERT INTO ITENS_VENDA VALUES(1,100,100,19)
INSERT INTO SETOR VALUES(3,'LIMPEZA','RESPONSAVEL PELO CUIDADO E ZELO DA HIGIENE DA EMPRESA.',16)

SELECT * FROM CLIENTES
SELECT * FROM VENDAS
SELECT * FROM PRODUTO
SELECT * FROM ITENS_VENDA
SELECT * FROM SETOR

--JOINS
SELECT CLI.[CPF],CLI.[NOME_CLIENTE],CLI.[EMAIL],VND.[PRODUTO_VENDIDO],VND.[PAGAMENTO]
FROM VENDAS AS VND
LEFT JOIN CLIENTES AS CLI
ON VND.[CLIENTE_COMPRADOR] = CLI.[CPF]
ORDER BY CLI.[NOME_CLIENTE];

--UNION
SELECT ID_VENDA FROM VENDAS
UNION ALL
SELECT ID_VENDA FROM ITENS_VENDA
ORDER BY ID_VENDA


--AGREG
SELECT VND.ID_VENDA,PRODUTO_VENDIDO,PROD.NOME_PRODUTO,ITN.QUANTIDADE_VENDIDA,
	COUNT(VND.CLIENTE_COMPRADOR) AS QTTD_COMPRADORES,
	MAX(ITN.QUANTIDADE_VENDIDA) AS MAIOR_VALOR_PAGO,
	SUM(PROD.PRE�O) AS SOMA_DE_TODOS_OS_PRECOS,
	AVG(PROD.PRE�O) AS MEDIA_PRE�OS

FROM VENDAS VND,PRODUTO PROD,ITENS_VENDA ITN
WHERE VND.PRODUTO_VENDIDO = PROD.ID_PRODUTO

GROUP BY VND.ID_VENDA,VND.PRODUTO_VENDIDO,PROD.NOME_PRODUTO
ORDER BY VND.ID_VENDA DESC, VND.PRODUTO_VENDIDO 