CREATE DATABASE EMPRESA_VENDAS;

CREATE TABLE CLIENTE(
  ID_CLIENTE INTEGER PRIMARY KEY NOT NULL,
  NOME VARCHAR(50),
  EMAIL VARCHAR(100),
  CPF INTEGER,
  TELEFONE INTEGER(15),
  ENDEREÇO VARCHAR(100)
  
);

CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INTEGER PRIMARY KEY NOT NULL,
	NOME VARCHAR(50),
	CNPJ TEXT,
	CONTATO INTEGER(15)
);
