USE EMPRESA_VENDAS

--VIEW 
/*CREATE VIEW [CLIENTES_VOGAIS] AS
SELECT NOME_CLIENTE,CPF
FROM CLIENTES
WHERE NOME_CLIENTE ='[AEIOU]%'*/
SELECT * FROM [CLIENTES_VOGAIS]


--VISUALIZANDO OS ÍNDICES
SELECT name
FROM sys.indexes
WHERE object_id = OBJECT_ID('CLIENTES')
AND name = 'cpf_client'


SELECT NOME_CLIENTE,CPF,EMAIL,ENDEREÇO,TELEFONE FROM CLIENTES