USE EMPRESA_VENDAS

--VIEW 
/*CREATE VIEW [CLIENTES_VOGAIS] AS
SELECT NOME_CLIENTE,CPF
FROM CLIENTES
WHERE NOME_CLIENTE ='[AEIOU]%'*/

/*ALTER VIEW [CLIENTES_VOGAIS] AS
SELECT NOME_CLIENTE,CPF,EMAIL,TELEFONE
FROM CLIENTES
WHERE NOME_CLIENTE LIKE'A%' OR
NOME_CLIENTE LIKE 'E%' OR
NOME_CLIENTE LIKE 'I%' OR
NOME_CLIENTE LIKE 'O%' OR
NOME_CLIENTE LIKE 'U%'*/
 
SELECT * FROM [CLIENTES_VOGAIS];


--VISUALIZANDO O ÍNDICE (index_nome)
SELECT S.name,S.type,S.is_unique,S.has_filter
FROM sys.indexes S
WHERE object_id = OBJECT_ID('CLIENTES')
AND name = 'index_nome'


SELECT NOME_CLIENTE,CPF,EMAIL,ENDEREÇO,TELEFONE FROM CLIENTES



